### PR TITLE
Enables Dev Container #117

### PR DESCRIPTION
**Pull request by rkrishnasanka**
Added vscode dev container settings. Should install the go package a couple of other vscode plugins. Currently, the dev container image uses a Ubuntu Focal Container and installs golang using the latest apt package `golang`.

This dev container also installs the following plugins:
1. `golang.go`
2. `ms-vsliveshare.vsliveshare-pack`
3. `redhat.vscode-yaml`
4. `yzhang.markdown-all-in-one`
5. `premparihar.gotestexplorer`
6. `github.vscode-pull-request-github`
7. `streetsidesoftware.code-spell-checker`
8. `eamodio.gitlens`

### CODE REVIEW

**Comment by TimothyStiles** [comment]
@rkrishnasanka I absolutely love the extensions you've found here. Does this also work with setting up local VScode environments?

**Comment by rkrishnasanka** [comment]
@TimothyStiles this is only for local VSCode Containers. I'm still figuring out how to make the webversions stick.

**Comment by rkrishnasanka** [comment]
@TimothyStiles Looks like the github codespaces will base off the initial version based on vscode container settings

**Comment by TimothyStiles** [comment]
> @TimothyStiles this is only for local VSCode Containers. I'm still figuring out how to make the webversions stick.

Awesome. We should probably include getting set up with this in the contributor's guidelines and I'll happily be the beta tester for that.

**Comment by TimothyStiles** [comment]
@rkrishnasanka testing out now. Couple of thoughts at first glance.

1. Installation time takes a while. At least a couple of minutes. Will it cache this or do it every time?

2. Docker container actually disconnected from VS code when I tried to open files and fails to render code. Pretty much has crashed and is unusable on my end. Also depends on the fact that end user already has docker installed on their machine. Probably not an issue for shipping on codespaces but looks like a headache install wise locally.

3. Localized containers won't run code that isn't pushed to remote git server. Huge slowdown with dev cycle time.

Is there a way to just ship extensions that we use as a single configured package and not worry about shipping a containerized environment? Go for the most part is stable in this sense and it may be more of a headache troubleshooting docker than just having devs install Go and run in their local environment.

**Comment by rkrishnasanka** [comment]
> @rkrishnasanka testing out now. Couple of thoughts at first glance.
> 
> 1. Installation time takes a while. At least a couple of minutes. Will it cache this or do it every time?

Well it'll only build it the first time it should be fine after that/I can check to make sure that this isn't the case all the time, try connecting it to it again, it wont go through docker build cycle

> 2. Docker container actually disconnected from VS code when I tried to open files and fails to render code. Pretty much has crashed and is unusable on my end. Also depends on the fact that end user already has docker installed on their machine. Probably not an issue for shipping on codespaces but looks like a headache install wise locally.

Do you have a screenshot of what happened ?

> 3. Localized containers won't run code that isn't pushed to remote git server. Huge slowdown with dev cycle time.
> 

Can you clarify what you mean by this? Basically, the way you use dev containers is by mounting whatever files you need onto the docker image so there should technically be no slowdown (vscode will mount your directory onto this docker image)

> Is there a way to just ship extensions that we use as a single configured package and not worry about shipping a containerized environment? Go for the most part is stable in this sense and it may be more of a headache troubleshooting docker than just having devs install Go and run in their local environment.

I don't think so...but there might be something that can be done here. I'm curious to see what your crash looks like

**Comment by rkrishnasanka** [comment]
I've added the ability to save the recommended extensions too

Jun-10-2021 00-02-11

**Comment by rkrishnasanka** [comment]
@TimothyStiles what kind of documentation would you want for this?

**Comment by TimothyStiles** [comment]
@rkrishnasanka I love all of this and I'm absolutely merging it!

**Pull request merged**
