### PR TITLE
Replaced the Seqhash sequencetype with Struct type argument instead of a plain string..

### PR DESCRIPTION
**Pull request by rkrishnasanka**
Replaced the sequenceType argument with an Enum. 

Currently using the direct const type enum. 

Addressing - #264

### CODE REVIEW

**Comment by rkrishnasanka** [comment]
@TimothyStiles can we close this?

**Comment by Koeng101** [comment]
@TimothyStiles fix the discord hooks!

**Comment by Koeng101** [comment]
Other than that, LGTM. Lots of little linter changes that I'm cool with

**Comment by TimothyStiles** [comment]
> @TimothyStiles fix the discord hooks!

on it now.

**Comment by rkrishnasanka** [comment]
@TimothyStiles I'm not sure why this is still failing. I merged your PR 😕

**Review by TimothyStiles — APPROVED** [review]
@rkrishnasanka this is an excellent PR. Thanks so much for migrating Poly away from ioutil which is being sunset by the official Go team. I'm going to re-add the go linter and merge!

**Comment by rkrishnasanka** [comment]
No issues ! Let's keep this rolling, let me know if there are other issues you need help on.

**Pull request merged**
