### PR TITLE
Improve Hash2Fragment by using a map to validate allowed sequence characters

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
## Changes in this PR
- Improves `Hash2Fragment` by using a map for more efficient validation of allowed sequence characters, discussion [here](https://github.com/TimothyStiles/poly/pull/398#discussion_r1393602404).

### Why are you making these changes?
General improvement.

### Are any changes breaking? (IMPORTANT)
No

## Pre-merge checklist
*All of these must be satisfied before this PR is considered
ready for merging. Mergeable PRs will be prioritized for review.*

* [ ] New packages/exported functions have docstrings.
* [x] New/changed functionality is thoroughly tested.
* [ ] New/changed functionality has a function giving an example of its usage in the associated test file. See `primers/primers_test.go` for what this might look like.
* [ ] Changes are documented in `CHANGELOG.md` in the `[Unreleased]` section.
* [x] All code is properly formatted and linted.
* [x] The PR template is filled out.

### CODE REVIEW

**Comment by TwFlem** [comment]
I saw the small alphabet size in the PR and was curious what that threshold might be when a map performs better list for another issue I'm working on. 

I created some benchmarks just to see what would happen with sequences with different possible alphabets of varying length. These were the results:

Map:
```
➜  poly git:(bwt) ✗ go test ./bwt  -bench=Map -benchmem
goos: linux
goarch: amd64
pkg: github.com/TimothyStiles/poly/bwt
cpu: 12th Gen Intel(R) Core(TM) i7-1260P
BenchmarkMapSmallAlphaWithNoMistakes-16                       63          18256289 ns/op          118586 B/op       1004 allocs/op
BenchmarkMapSmallAlphaWithSomeMistakes-16                     36          32899572 ns/op          207527 B/op       1758 allocs/op
BenchmarkMapSmallAlphaWithManyMistakes-16                     43          27737360 ns/op          173744 B/op       1471 allocs/op
BenchmarkMapCompleteAlphaWithNoMistakes-16                    31          40500822 ns/op          240999 B/op       2041 allocs/op
BenchmarkMapCompleteAlphaWithSomeMistakes-16                  32          35741798 ns/op          233468 B/op       1977 allocs/op
BenchmarkMapCompleteAlphaWithManyMistakes-16                  40          29150322 ns/op          186774 B/op       1582 allocs/op
BenchmarkMapCompleteAlphaOopsAllMistakes-16                   54          22971922 ns/op          138351 B/op       1172 allocs/op
```

Contains:
```
➜  poly git:(bwt) ✗ go test ./bwt  -bench=Contains -benchmem
goos: linux
goarch: amd64
pkg: github.com/TimothyStiles/poly/bwt
cpu: 12th Gen Intel(R) Core(TM) i7-1260P
BenchmarkContainsSmallAlphaWithNoMistakes-16                 108          11106460 ns/op           69175 B/op        586 allocs/op
BenchmarkContainsSmallAlphaWithSomeMistakes-16                52          22495471 ns/op          143672 B/op       1217 allocs/op
BenchmarkContainsSmallAlphaWithManyMistakes-16                55          22519629 ns/op          135836 B/op       1150 allocs/op
BenchmarkContainsCompleteAlphaWithNoMistakes-16               87          13739731 ns/op           85873 B/op        727 allocs/op
BenchmarkContainsCompleteAlphaWithSomeMistakes-16             52          22516387 ns/op          143672 B/op       1217 allocs/op
BenchmarkContainsCompleteAlphaWithManyMistakes-16             49          24487380 ns/op          152469 B/op       1291 allocs/op
BenchmarkContainsCompleteAlphaOopsAllMistakes-16              94          11535203 ns/op           79478 B/op        673 allocs/op
```

Contains happened to perform better in these bench marks. I wonder if caching starts to come into play with all the different data involved. Including the benchmark code and cpu profile in the comment.

**Comment by TwFlem** [comment]
cpu profile

cpu map-vs-contains inseqHashFn

**Comment by Koeng101** [comment]
> Also, Contains seems to be more performant in the Small/Complete alphabet with no mistakes case, which seems like it would be the most common case.

Interesting! @matiasinsaurralde Do you have any thoughts on this? The use case of no-mistakes is definitely the most common by an order of magnitude or more

**Comment by matiasinsaurralde** [comment]
@Koeng101 Agree with that, feel free to discard/ignore my suggestion

**Pull request closed without merging**
